# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/richh/sprite_test/sprite_test.srcs/sources_1/ip/watermellon_rom/watermellon_rom.xci
# IP: The module: 'watermellon_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/richh/sprite_test/sprite_test.gen/sources_1/ip/watermellon_rom/watermellon_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'watermellon_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/richh/sprite_test/sprite_test.srcs/sources_1/ip/watermellon_rom/watermellon_rom.xci
# IP: The module: 'watermellon_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/richh/sprite_test/sprite_test.gen/sources_1/ip/watermellon_rom/watermellon_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'watermellon_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
